name: download

on:
  schedule:
    - cron: '8 23 * * *'

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: download latest
          uses: madsportslab/nba-download@v1
        - name: list downloaded files
          run: |
            ls -la
